---
pool: 
  vmImage: 

stages:
  - stage: buildjob
    jobs:
      - job: buildjob
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: pom.xml
              goals: mvn clean package
              javaHomeOption: '1.17'

  
    