---
pool: 
  vmImage: ubuntu-24.04
trigger: 
  - main

stages:
  - stage: buildjob
    jobs:
      - job: buildjob
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: pom.xml
              goals: mvn package
              javaHomeOption: '1.17'

  
    