---
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
    - name: web
      image: nginx:1.27


---

---
apiVersion: v1
kind: Pod
metadata:
  name: activity-2
spec:
  containers:
    - name: web
      image: nginx:1.27